### ISSUE TITLE
#更新抽卡记录  命令异常

### ISSUE THREAD

**Issue by xueqi5201314** [ctrlcvs/xiaoyao-cvs-plugin#101]
![Screenshot_20230601_233331.jpg](https://github.com/ctrlcvs/xiaoyao-cvs-plugin/assets/108047693/8fa6b95a-1988-48fc-9d82-a7815a52c251)

![6e8c592137629d31.jpg](https://github.com/ctrlcvs/xiaoyao-cvs-plugin/assets/108047693/13fa3a11-f01a-4dfc-96e4-c0959c5e475b)

控制台没有报错信息

**Comment by xueqi5201314** [comment]
stoken，cookie 都绑定了，昨天还能更新，今天就不行了

**Comment by xueqi5201314** [comment]
![Screenshot_20230601_234550.jpg](https://github.com/ctrlcvs/xiaoyao-cvs-plugin/assets/108047693/cd2ee140-41ae-4466-9d46-5c3a5568c380)

刚刚试了重新绑定，发现 #扫码登录 后stoken信息没有绑定到，提示未绑定stoken

**Comment by ctrlcvs** [comment]
喵崽的问题，建议更新主体

**Comment by xueqi5201314** [comment]
> 喵崽的问题，建议更新主体

昨天更新了，可以用了，但是自动签到不好使了π_π
