### ISSUE TITLE
查询图鉴不行，配置和体力可以

### ISSUE THREAD

**Issue by Enderhz** [ctrlcvs/xiaoyao-cvs-plugin#14]
![image](https://user-images.githubusercontent.com/103828674/187020837-ed438f9f-8cba-45df-83c1-5c26c929cc59.png)

yunzai 版本 v3 是太高了吗 **;((**

**Comment by ctrlcvs** [comment]
需要设置目录开启、具体看图鉴设置吧开启功能就行

**Comment by Enderhz** [comment]
收到，这就试试
&nbsp;


\ue101
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月27日(星期六) 晚上6:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ctrlcvs/xiaoyao-cvs-plugin] 查询图鉴不行，配置和体力可以 (Issue #14)





 
需要设置目录开启、具体看图鉴设置吧开启功能就行

**Comment by Enderhz** [comment]
solved thx <3
love from china
&nbsp;


\ue101
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月27日(星期六) 晚上6:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ctrlcvs/xiaoyao-cvs-plugin] 查询图鉴不行，配置和体力可以 (Issue #14)





 
需要设置目录开启、具体看图鉴设置吧开启功能就行
