### ISSUE TITLE
【BUG】更新抽卡记录没有反应

### ISSUE THREAD

**Issue by XpastaX** [ctrlcvs/xiaoyao-cvs-plugin#140]
输入#更新抽卡记录后，回复“抽卡记录获取中请稍等...”。然后就没有反应，Yunzai后台没有任何相关报错。

[TRSSYz][21:35:34.526][MARK] [1912315276] OneBotv11(QQ) go-cqhttp-v1.2.0_linux_amd64-go1.20.8 已连接
[TRSSYz][21:35:38.754][INFO] [1912315276 <= 910104452] 好友消息：[xxx] #更新抽卡记录
[TRSSYz][21:35:38.775][ERRO] [unhandledRejection] [ErrorReply: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.] {
  [stack]: [Getter/Setter: undefined],
  [message]: 'MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.'
}
[TRSSYz][21:35:39.286][INFO] [1912315276 => 910104452] 发送好友消息：[{"type":"text","data":{"text":"抽卡记录获取中请稍等..."}}]
[TRSSYz][21:35:39.291][ERRO] [unhandledRejection] [ErrorReply: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.] {
  [stack]: [Getter/Setter: undefined],
  [message]: 'MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.'
}
[TRSSYz][21:35:39.642][ERRO] [xiaoyao-cvs-plugin][dispatch]
[TRSSYz][21:35:39.643][ERRO] undefined

某次手动pull更新逍遥插件之后就不好用了。
请问有什么办法可以拿到后台的debug记录吗？

**Comment by YsKiKi** [comment]
你这个好像是redis禁止写入数据导致的，请尝试重启redis，查看redis日志

**Comment by XpastaX** [comment]
解决了，好像是redis卡死了。
