### ISSUE TITLE
扫码登录解决办法（方法是大佬提供的）

### ISSUE THREAD

**Issue by jiuyixian** [ctrlcvs/xiaoyao-cvs-plugin#150]
xiaoyao-cvs-plugin\model\mys\mystool.js   的第18行 数字改成8后，重启就行了

第18行代码  const app_id = 4   将数字改成8，保存重启就行了

标识符 参考: https://github.com/UIGF-org/mihoyo-api-collect/blob/main/hoyolab/login/qrcode_hk4e.md#%E7%94%9F%E6%88%90%E4%BA%8C%E7%BB%B4%E7%A0%81

**Comment by 244030119** [comment]
修复了，这个办法真不错

**Comment by Oishiimono** [comment]
感谢大佬

**Comment by lingxiu11** [comment]
感谢大佬
