### ISSUE TITLE
windows正常linux图片出不来也没报错

### ISSUE THREAD

**Issue by 1011382654** [ctrlcvs/xiaoyao-cvs-plugin#18]
感觉就好像命令没命中一样

**Comment by ctrlcvs** [comment]
具体麻烦截图

> 感觉就好像命令没命中一样

**Comment by 1011382654** [comment]
> 

这是linux下的两个命令对比,其中xiaoyao插件没有输出
http://ww3.sinaimg.cn/large/008p0nyfly1h6rc2c0cozj30jj0e2goj.jpg

这是win下的输出正常
http://ww3.sinaimg.cn/large/008p0nyfly1h6rc2xvu50j30pu06v0th.jpg

**Comment by 1011382654** [comment]
> 具体麻烦截图
> 
> > 感觉就好像命令没命中一样

这是linux下的两个命令对比,其中xiaoyao插件没有输出
http://ww3.sinaimg.cn/large/008p0nyfly1h6rc2c0cozj30jj0e2goj.jpg

这是win下的输出正常
http://ww3.sinaimg.cn/large/008p0nyfly1h6rc2xvu50j30pu06v0th.jpg

**Comment by ctrlcvs** [comment]
> > 具体麻烦截图
> > > 感觉就好像命令没命中一样
> 
> 这是linux下的两个命令对比,其中xiaoyao插件没有输出 http://ww3.sinaimg.cn/large/008p0nyfly1h6rc2c0cozj30jj0e2goj.jpg
> 
> 这是win下的输出正常 http://ww3.sinaimg.cn/large/008p0nyfly1h6rc2xvu50j30pu06v0th.jpg

图鉴设置需要开启第二个目录的东西，其次检查图片资源是否下载全，另外的话默认是不会输出日志的

**Comment by 1011382654** [comment]
> > > 具体麻烦截图
> > > > 感觉就好像命令没命中一样
> > 
> > 
> > 这是linux下的两个命令对比,其中xiaoyao插件没有输出 http://ww3.sinaimg.cn/large/008p0nyfly1h6rc2c0cozj30jj0e2goj.jpg
> > 这是win下的输出正常 http://ww3.sinaimg.cn/large/008p0nyfly1h6rc2xvu50j30pu06v0th.jpg
> 
> 图鉴设置需要开启第二个目录的东西，其次检查图片资源是否下载全，另外的话默认是不会输出日志的

还真是资源没下全！武器110条就是没有风鹰剑
