### ISSUE TITLE
为什么我插件生成的图片经常没有显示文字呢？

### ISSUE THREAD

**Issue by 1776304537** [ctrlcvs/xiaoyao-cvs-plugin#20]
![QQ图片20221013122929](https://user-images.githubusercontent.com/24807330/195502082-a2d24ba4-d939-4205-bbb3-96cf3e0cb700.jpg)
![QQ图片20221013122936](https://user-images.githubusercontent.com/24807330/195502089-97cf59e1-bf8a-4275-926a-375740ff0e19.jpg)
![QQ图片20221013122940](https://user-images.githubusercontent.com/24807330/195502091-89b1d432-3f92-45cf-9016-e9c9bc077e29.jpg)
![QQ图片20221013123048](https://user-images.githubusercontent.com/24807330/195502097-b1ece3e1-b6b0-4156-9f3f-d5480074f77d.jpg)
有时候有有时候是没有的

**Comment by ctrlcvs** [comment]
渲染时机问题后续的版本改了

**Comment by 1776304537** [comment]
我更新可以直接下载压缩包传到服务器上么？用指令下载太慢了
