### ISSUE TITLE
新账号绑定stoken报错，之前的绑定过的账号没问题

### ISSUE THREAD

**Issue by GoverSky** [ctrlcvs/xiaoyao-cvs-plugin#21]
版本:最新版
问题：之前绑定的没有问题，新绑定的就不行
<img width="840" alt="image" src="https://user-images.githubusercontent.com/16715284/195864594-aee9d6bf-c981-4a0b-861f-4495ed291d56.png">
我参照其他的数据结构手动创建yaml 是成功的

**Comment by ctrlcvs** [comment]
更新下
