### ISSUE TITLE
启用插件后python异常占用内存

### ISSUE THREAD

**Issue by Richo-lu** [ctrlcvs/xiaoyao-cvs-plugin#24]
![JSI}TS080LB(JO6QT)U7VSL](https://user-images.githubusercontent.com/71910448/198286560-35e94e4c-080b-4474-8dca-23e81c639008.png)
启动后会自动弹出一个python应用poetry.exe，占用内存非常高，不知道是什么原因

**Comment by ctrlcvs** [comment]
我的plugin不是py的。。。

**Comment by Richo-lu** [comment]
可能是宵鸟的崩坏三签到和这个的崩坏三签到冲突了，我把这个关了它就没了

**Comment by ctrlcvs** [comment]
> 可能是宵鸟的崩坏三签到和这个的崩坏三签到冲突了，我把这个关了它就没了
删除图鉴插件就行
