### ISSUE TITLE
签到推送开关设置失效

### ISSUE THREAD

**Issue by chen8945** [ctrlcvs/xiaoyao-cvs-plugin#25]
在这一次更新后哪怕推送设置为 false，签到成功后依然会推送信息至主人QQ，在这次更新前一切正常
![](https://p.qlogo.cn/hy_personal/3e28f14aa0516842cfbabf5dab3594357b22864e9f6d411df02a77ddf739040e/0.jpg)
![](https://p.qlogo.cn/hy_personal/3e28f14aa0516842cfbabf5dab359435b9843808966e80d8f87b480ccb10ab6a/0.jpg)
以下为我的设置
![](https://p.qlogo.cn/hy_personal/3e28f14aa0516842cfbabf5dab359435e1d837d6d194c6b8f1651bc144f155db/0.jpg)

**Comment by ctrlcvs** [comment]
关闭签到才会不推送主人消息，那个推送是推送用户的
