### ISSUE TITLE
希望大佬能增添多账号体力同时查询的功能

### ISSUE THREAD

**Issue by CUZNIL** [ctrlcvs/xiaoyao-cvs-plugin#26]
现在如果有多账号需要查询体力的话，只能手动操作，例如我有俩个账号就是这样
![X` IZACIU%W$P}D Y4W@B33](https://user-images.githubusercontent.com/76582404/198892096-3c6c96d6-10a1-4cde-99f0-4e1ad59ef716.png)

希望能通过一条指令完成这些手动操作，比如`#全部体力`，自动依次切换当前QQ号绑定的多个ck然后查询体力直接返回对应的多个图片，或者以表格形式存储好后制图返回一张图片这样。
![XITSB17J(GH1 B9O{GPO 5W](https://user-images.githubusercontent.com/76582404/198892296-baf1fea3-c61d-426f-a17b-1ed588cb8667.png)

**Comment by ctrlcvs** [comment]
已添加，可通过`#多体力`查询

**Comment by CUZNIL** [comment]
> 已添加，可通过`#多体力`查询

好耶！谢谢大佬
