### ISSUE TITLE
提示请重新绑定stoken但是拿旧的再发一遍又可以像这种情况能否优化下

### ISSUE THREAD

**Issue by 1011382654** [ctrlcvs/xiaoyao-cvs-plugin#28]

**Comment by ctrlcvs** [comment]
发送的cookies?还是stoken?麻烦截图说明问题

**Comment by 1011382654** [comment]
> 发送的cookies?还是stoken?麻烦截图说明问题

我自己也就碰到过一次可惜没取证，但是经常看到别人更新抽卡记录提示重新绑定stoken，根据我自己的情况配置完一次应该很久都不用重绑的

**Comment by ctrlcvs** [comment]
已优化 其次绑定sk如果没有提示绑定成功 你发多少次都是会提示重新绑定stoken
