### ISSUE TITLE
渡火套4件效果描述与游戏内不一致

### ISSUE THREAD

**Issue by PrussianBlueCN** [ctrlcvs/xiaoyao-cvs-plugin#29]
![85AC9C06-8055-47B9-846C-78795536DA4C](https://user-images.githubusercontent.com/110645427/201532552-e5014d58-2348-4710-8802-97a4022c79e3.png)
![B04FD915-4183-47E9-8569-3B25F7F750B6](https://user-images.githubusercontent.com/110645427/201532556-f0e7e89c-8279-43a6-bcc4-68f91f952762.png)

游戏内和米游社百科确实都没有提燃烧，不过实际有没有燃烧我也不知道。。

**Comment by ctrlcvs** [comment]
更新图鉴
