### ISSUE TITLE
#图鉴插件更新

### ISSUE THREAD

**Issue by RockRadix** [ctrlcvs/xiaoyao-cvs-plugin#3]
图鉴更新至最新（1.0.8）发生#图鉴插件更新-可一直更新，并没有提示以达到最新无法更新。

**Comment by ctrlcvs** [comment]
尝试手动更新排查，如果是国内网络请换成gitee如果是海外的请换成github

**Comment by RockRadix** [comment]
图鉴插件本身在1.0.8版本，但是在对机器人发送#图鉴插件更新依旧可以更新，但不会提示已到达最新版本，从而阻止本次更新。
![image](https://user-images.githubusercontent.com/99504275/177928507-fcf3b605-8f76-4b93-9297-ce6c8da5b8fa.png)

**Comment by RockRadix** [comment]
图鉴插件本身在1.0.8版本，但是在对机器人发送#图鉴插件更新依旧可以更新，但不会提示已到达最新版本，从而阻止本次更新。
![image](https://user-images.githubusercontent.com/99504275/177928900-a9cb1f1a-2c4a-44aa-93a6-74ef0a64e4ca.png)
![image](https://user-images.githubusercontent.com/99504275/177928855-38aae4ae-26c5-41f9-97d3-acf56eaabc4a.png)
