### ISSUE TITLE
3.3新增的食谱是不是一直没更新图鉴

### ISSUE THREAD

**Issue by fsqhn** [ctrlcvs/xiaoyao-cvs-plugin#30]
如题，已进行过多次#图鉴更新，但部分须弥新食谱依旧没有图鉴。
目前能确认的包括：阿如拌饭、蔷薇奶糊、千层酥酥、枣椰蜜糖、烤肉卷等及其对应的特色料理都没有。米圆塔有图鉴但对应的赛诺特色料理决斗之魂却没有。

**Comment by ctrlcvs** [comment]
图鉴作者因为某些原因目前是只维护角色、怪物、圣遗物图鉴 其余图鉴目前大概率随缘维护

**Comment by fsqhn** [comment]
好的，谢谢。
