### ISSUE TITLE
在Template里添加模板是否有效

### ISSUE THREAD

**Issue by ABT98421** [ctrlcvs/xiaoyao-cvs-plugin#32]
尽管Template里有从[仓库](https://github.com/SmallK111407/BJT-Template)下载的129个模板，设置了图鉴模板随机，但生成体力图片时有95%概率使用/dailyNote/background_image/里的模板，和璃月稻妻等不存在本地的模板
（但是偶尔确实会使用Template里的模板）
![image](https://user-images.githubusercontent.com/78371203/204710483-f9794fc8-64f2-4832-9ad8-4f181b7d161e.png)

**Comment by ctrlcvs** [comment]
> 尽管Template里有从[仓库](https://github.com/SmallK111407/BJT-Template)下载的129个模板，设置了图鉴模板随机，但生成体力图片时有95%概率使用/dailyNote/background_image/里的模板，和璃月稻妻等不存在本地的模板 （但是偶尔确实会使用Template里的模板） ![image](https://user-images.githubusercontent.com/78371203/204710483-f9794fc8-64f2-4832-9ad8-4f181b7d161e.png)

随机的概率是从模板一跟模板二 随机选一个（模板1或者模板2），所以说并不是按照你多少模板图来的

**Comment by ABT98421** [comment]
> 随机的概率是从模板一跟模板二 随机选一个（模板1或者模板2），所以说并不是按照你多少模板图来的
那现在xiaoyao-cvs-plugin是不是不会调用Template里的模板，而只有默认的那些

**Comment by ctrlcvs** [comment]
> > 随机的概率是从模板一跟模板二 随机选一个（模板1或者模板2），所以说并不是按照你多少模板图来的
> 
> 那现在xiaoyao-cvs-plugin是不是不会调用Template里的模板，而只有默认的那些

你最开始都说了会调用,为什么还要问会不会调用

**Comment by ABT98421** [comment]
将体力模板类型改为2已解决
