### ISSUE TITLE
深林的记忆和饰金之梦部分关键词不能触发，祭冰礼冠与祭水礼冠描述错位

### ISSUE THREAD

**Issue by jiut** [ctrlcvs/xiaoyao-cvs-plugin#33]
一下关键词不能触发：
草套

精通套
反应套
元素反应套

**Comment by ctrlcvs** [comment]
别名有问题后续会另外写入文件支持，最近一段时间确实不想改这里，可以尝试自行修改

图鉴描述错位已经改了 更新图鉴就行
