### ISSUE TITLE
绑定stoken问题

### ISSUE THREAD

**Issue by Misakami** [ctrlcvs/xiaoyao-cvs-plugin#35]
根据教程获取了stoken发送给机器人后 更新抽卡记录提示登录stoken失效重新绑定

**Comment by ctrlcvs** [comment]
尝试更新后再试，或者是先用`#刷新ck` 再用`#更新抽卡记录`

**Comment by Misakami** [comment]
> 尝试更新后再试，或者是先用`#刷新ck` 再用`#更新抽卡记录`

插件重新pull之后，重新获取stoken。发送#刷新ck 返回请求异常: Something went wrong

**Comment by ctrlcvs** [comment]
目前更新最新是否可以绑定，如果不行的话是否可以提供数据供我测试？
 可以的麻烦加群`544570609`反馈 目前兼容是做不到全面支持的，并不是跟米游社开发一样有文档之类的，这些接口跟数据都是抓包来测试的，如果说一直不行可以尝试加群提供数据测试以优化问题

**Comment by Misakami** [comment]
> 目前更新最新是否可以绑定，如果不行的话是否可以提供数据供我测试？ 可以的麻烦加群`544570609`反馈 目前兼容是做不到全面支持的，并不是跟米游社开发一样有文档之类的，这些接口跟数据都是抓包来测试的，如果说一直不行可以尝试加群提供数据测试以优化问题

之前有点事被墙了，最新的代码能正常更新了。谢谢
