### ISSUE TITLE
绑定stoken问题

### ISSUE THREAD

**Issue by yiyule10** [ctrlcvs/xiaoyao-cvs-plugin#38]
如果发送cookie，包含多段数据，就会提示“绑定Stoken失败，异常：登录失效，请重新登录”
示例：stoken=xxxxx;stuid=xxxxx;ltoken=xxxxx;ltuid=xxxxx;account_id=xxxxx;cookie_token=xxxxx

发送此cookie的前三段，就会提示“绑定成功”
示例：stoken=xxxxx;stuid=xxxxx;ltoken=xxxxx

**Comment by ctrlcvs** [comment]
首先cookie跟stoken是两个东西，其次的话不要把cookie跟stoken合并一起发送


> 如果发送cookie，包含多段数据，就会提示“绑定Stoken失败，异常：登录失效，请重新登录” 示例：stoken=xxxxx;stuid=xxxxx;ltoken=xxxxx;ltuid=xxxxx;account_id=xxxxx;cookie_token=xxxxx
> 
> 发送此cookie的前三段，就会提示“绑定成功” 示例：stoken=xxxxx;stuid=xxxxx;ltoken=xxxxx

**Comment by yiyule10** [comment]
> 首先cookie跟stoken是两个东西，其次的话不要把cookie跟stoken合并一起发送
> 
> > 如果发送cookie，包含多段数据，就会提示“绑定Stoken失败，异常：登录失效，请重新登录” 示例：stoken=xxxxx;stuid=xxxxx;ltoken=xxxxx;ltuid=xxxxx;account_id=xxxxx;cookie_token=xxxxx
> > 发送此cookie的前三段，就会提示“绑定成功” 示例：stoken=xxxxx;stuid=xxxxx;ltoken=xxxxx

好的，感谢科普
