### ISSUE TITLE
命令失效问题

### ISSUE THREAD

**Issue by yibeiliang151** [ctrlcvs/xiaoyao-cvs-plugin#4]
角色和武器图鉴和体力背景能用，但是原魔、食物、圣遗物都用不了，发了命令没反应，怎么弄呀

**Comment by ctrlcvs** [comment]
#图鉴设置  中有个叫目录的打开就行了

**Comment by yibeiliang151** [comment]
> 



> #图鉴设置中叫目录的打开就行了

打开了也还是不行诶，呜呜呜

**Comment by yibeiliang151** [comment]
*可通过修改init方法调用新实现版体力js
    *具体将* *YunzaiApps.dailyNote.DailyNoteTask() **方法改为**YunzaiApps["plugin_xiaoyao-cvs-plugin"].DailyNoteTask()**

这个是在哪里改呀..呜呜呜，找不到

**Comment by ctrlcvs** [comment]
init.js在lib目录下面，打开不行可能是关闭功能的问题，#重置关闭功能，后再试试

**Comment by yibeiliang151** [comment]
> 

好耶，修好啦，谢谢大佬
