### ISSUE TITLE
#扫码登录 复读机bug

### ISSUE THREAD

**Issue by CUZNIL** [ctrlcvs/xiaoyao-cvs-plugin#44]
![~0HY@`Z70A_CZY DDZC11ZQ](https://user-images.githubusercontent.com/76582404/212472214-a5ca77fa-39a3-4906-b0b3-300f06e31fb6.png)
如图所示，如果用户扫码后停留未点击确认登录会一直复读，就算退出米游社的确认登录窗口也会。
这会导致如果用户扫码后手贱不确认登录就滑走了，bot确认不到登录会一直复读，用户想确认登录也不行了，最后只能重启bot。
emm 我感觉“请确认登录”的提示可以改一下频率，现在好像是每隔5-6s复读一次，频率太高了。
个人觉得这个频率保持20s能起到提醒的作用，再长有点吵。

**Comment by ctrlcvs** [comment]
已加入缓存机制，目测是只回复一次
