### ISSUE TITLE
那个xxx在哪里的地图材料查询可否增加对渊下宫等单独地图的支持

### ISSUE THREAD

**Issue by Inky-Moon** [ctrlcvs/xiaoyao-cvs-plugin#45]
好像只能查询大世界的，像渊下宫还有层岩地下这种单独的地图查询不了

**Comment by Inky-Moon** [comment]
现在使用该功能时控制台会提示结果图片的url，我用普通宝箱作为例子把这个url放到浏览器上测试了下：
首先我查到了这个api有三个可配置的字段，这个插件里面用了两个
https://map.minigg.cn/map/get_map?resource_name=普通的宝箱&is_cluster=false
然后还有一个map_id的字段，测试了下这个字段就是切换地图的。如果添加map_id=7出来就是渊下宫的结果，7改成9就是层岩巨渊地下矿区的结果。也就是这样：
渊下宫宝箱：https://map.minigg.cn/map/get_map?resource_name=普通的宝箱&is_cluster=false&map_id=7
层岩地下宝箱：https://map.minigg.cn/map/get_map?resource_name=普通的宝箱&is_cluster=false&map_id=9
至于地图对应的map_id如何找，我也试了下，就是在观测枢大地图工具的url里面，“/map/”字段的后面有个数字，这个就是当前地图对应的map_id。比如大世界对应的url是https://webstatic.mihoyo.com/ys/app/interactive-map/?lang=zh-cn#/map/2，这里可以发现大世界的map_id是2。

**Comment by ctrlcvs** [comment]
目前支持查询全图的数据，没事闲着别来杠

**Comment by ctrlcvs** [comment]
至于为什么不加识别因为这个识别逻辑在接口另外写了支持
