### ISSUE TITLE
刷新ck后无回复，后台显示正常刷新后报错

### ISSUE THREAD

**Issue by shikong0516** [ctrlcvs/xiaoyao-cvs-plugin#51]
刷新ck后不回复消息，后台报错，目前在两个不同环境的机器人测试下都出现了这个问题
![图片](https://user-images.githubusercontent.com/119775321/218132787-6731b35e-1fd5-4d05-8a4d-dda5a1d36db7.png)

**Comment by ctrlcvs** [comment]
这个是合并转发消息发送失败导致的，目前无法解决

**Comment by shikong0516** [comment]
> 这个是合并转发消息发送失败导致的，目前无法解决

好的，谢谢
