### ISSUE TITLE
请教：云原神自动签到开关相关

### ISSUE THREAD

**Issue by MWTJC** [ctrlcvs/xiaoyao-cvs-plugin#55]
- 如题，我从插件的`config.yaml`文件里发现了云原神自动签到的功能，在`config.yaml`设置云原神自动签到为`true`后，似乎依然不能云原神自动签到，故猜测还存在一层用户开关，但在`#图鉴帮助`与`#图鉴版本`中我并没找到有关“云原神自动签到”的用户开关…

- 另外`config.yaml`第26行，疑似将`云原神签到定时任务`写成了`米游社签到定时任务`，仅告知。

**Comment by ctrlcvs** [comment]
经测试目前是可以签的

**Comment by JadeVane** [comment]
请问最后解决了吗？我想实现指定的帐号每天自动签到，未设置的帐号就不签到，但没找到在那里设置
