### ISSUE TITLE
伟大的c佬，帮帮忙吧

### ISSUE THREAD

**Issue by hbj2457** [ctrlcvs/xiaoyao-cvs-plugin#57]
可以添加一个关闭合并转发消息的功能吗，频道没办法显示出来，比如刷新ck和更新抽卡记录，只要有反应就行，不需要特别长

**Comment by ctrlcvs** [comment]
我的插件合并转发消息基本上都在plugin/model/mys/utils.js里面有个合并转发的，你可以尝试自己改那个方法，要么的话你重载或者是重写生成转发消息的方法也可以
