### ISSUE TITLE
账密登录验证问题

### ISSUE THREAD

**Issue by GOOD-AN** [ctrlcvs/xiaoyao-cvs-plugin#62]
账号密码登录时，返回验证链接，点进去提示`old challenge`
![image](https://user-images.githubusercontent.com/53306377/227104114-0aff2de5-ceae-4b23-8b45-e2bdef48884c.png)

**Comment by ctrlcvs** [comment]
一次链接只有第一次打开的时候生效，后续打开的话都会提示这个

**Comment by GOOD-AN** [comment]
嗯，我想到了，所以问过，他是第一次打开，那可能是运行异常吧，后续再看看吧。
