### ISSUE TITLE
#扫码登录 引发机器人风控解决建议

### ISSUE THREAD

**Issue by Aliorpse** [ctrlcvs/xiaoyao-cvs-plugin#63]
如题，开放扫码登录功能时引发机器人风控，建议改为转发消息发送二维码或做个动态网页 #扫码登录 后在网页上放二维码用于绑定账号

**Comment by Aliorpse** [comment]
转发消息发送二维码 二维码发送者是触发指令的那个

**Comment by ctrlcvs** [comment]
想法不错，我这边建议你自己去实现
