### ISSUE TITLE
获取武器记录失败

### ISSUE THREAD

**Issue by AGOU12138** [ctrlcvs/xiaoyao-cvs-plugin#64]
执行#更新抽卡记录命令后，只能获取角色记录和常驻记录，无法获取武器记录
![image](https://user-images.githubusercontent.com/114103774/227826114-3a0f6950-45c5-42cf-a0fd-64effc71c8ff.png)

**Comment by ctrlcvs** [comment]
建议手动导出链接去绑定【指令：#导出抽卡记录】，或者是自行去游戏内或者是去别的地方拿链接，或者是获取多次，其次这个指令只是伪造了一个链接而已并不是帮你去获取记录，获取的逻辑依旧是走的云崽
