### ISSUE TITLE
#扫码登陆 问题

### ISSUE THREAD

**Issue by xueqi5201314** [ctrlcvs/xiaoyao-cvs-plugin#69]
发送 #扫码登陆 后没有来得及扫码，结果撤回了，再次发送，就提示前置扫码未完成，请勿重复
![image](https://user-images.githubusercontent.com/108047693/229348738-e138b12f-d1a9-4239-bca3-ac974f55b3d7.png)

**Comment by Oishiimono** [comment]
有没有可能码停留久了容易被举报封号（警觉

**Comment by xueqi5201314** [comment]
现在没事了，忘了一直没扫会过期
