### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by MLYSCEM** [ctrlcvs/xiaoyao-cvs-plugin#7]
![IMG_20220729_140301](https://user-images.githubusercontent.com/109544711/181693272-fe6aca70-1ca0-47c1-8929-d1b279a9e474.jpg)
如图

**Comment by ctrlcvs** [comment]
V2
cnpm install promise-retry
cnpm install superagent

**Comment by ctrlcvs** [comment]
目前的话只需要引入这块文件就行了，具体的话首页有说明依赖缺少需要怎么操作

**Comment by MLYSCEM** [comment]
ok

**Comment by MLYSCEM** [comment]
大佬我问一下我不太明白在哪里输入安装依赖的命令

**Comment by ctrlcvs** [comment]
云崽根目录
