### ISSUE TITLE
#扫码登录 后，使用#刷新ck 拿到的cookie依然是失效的

### ISSUE THREAD

**Issue by AshenAshes** [ctrlcvs/xiaoyao-cvs-plugin#74]
起因是群友想查#体力，然后一直返回米游社验证码那个报错，然后用#ck 命令查了下发现是cookie失效了。但是直接用#刷新ck得到的ck还是失效的，于是让他删除stoken重新#扫码登录后再看看ck，但是还是失效的。删了ck后再刷新也是失效的，想问下大佬应该怎么解决？
![QQ图片20230424011341](https://user-images.githubusercontent.com/39981645/233854612-09af9644-23da-44fa-ae2e-80b379b3407f.jpg)

**Comment by AshenAshes** [comment]
#刷新ck后，发#签到和#探索度都能用，但是一发#体力就会报验证码，去米游社检查就会发现体力界面没有弹验证码。用#ck检查会报cookie失效，就很奇怪。

**Comment by AshenAshes** [comment]
大佬你如果打算查，我可以给你提供我的米游社小号，能稳定复现这个问题orz

**Comment by ctrlcvs** [comment]
首先失效跟验证码你要区分开来，其次的话`刷新ck`是没有问题，只是模拟了获取ck操作，
另外`#ck`指令的判定失效情况有两种，一直是失效一直是验证码，
你前往米游社没有验证码很正常，因为这个验证码是根据设备来的，要解除这种情况的话可以尝试来回多刷新一下体力跟角色页面，会有验证码弹出的

**Comment by AshenAshes** [comment]
谢谢大佬的详细解答，帮大忙了！Thanks♪(･ω･)ﾉ
