### ISSUE TITLE
刷新ck报错

### ISSUE THREAD

**Issue by XiaoFuOS** [ctrlcvs/xiaoyao-cvs-plugin#79]
![image](https://user-images.githubusercontent.com/103229747/235850579-d722c67e-6b73-4994-9ce8-bade4a74d304.png)
啥问题鸭

**Comment by XiaoFuOS** [comment]
能刷新成功，但是报错，群里也没发送刷新成功的转发消息

**Comment by ctrlcvs** [comment]
合并转发消息发送失败了，估计是icqq问题可以尝试更新一次icqq版本库

**Comment by XiaoFuOS** [comment]
> 合并转发消息发送失败了，估计是icqq问题可以尝试更新一次icqq版本库

icqq 0.3.1 的，貌似还是不行

**Comment by XiaoFuOS** [comment]
> 合并转发消息发送失败了，估计是icqq问题可以尝试更新一次icqq版本库

![image](https://user-images.githubusercontent.com/103229747/236623605-1040e3fa-0aa7-44e6-9a72-eb21fa78a633.png)
刷新失败的会显示，成功的不显示

**Comment by subreast** [comment]
![Y)A_`FZB)MFIH%F}T6JIC8N](https://github.com/ctrlcvs/xiaoyao-cvs-plugin/assets/132317906/012cf653-462d-4dbb-8a66-d474065f9ed2)
求帮助

**Comment by XiaoFuOS** [comment]
> ![Y)A_`FZB)MFIH%F}T6JIC8N](https://user-images.githubusercontent.com/132317906/237308462-012cf653-462d-4dbb-8a66-d474065f9ed2.png) 求帮助

感觉你的保存和我的一样，解决了没

**Comment by XiaoFuOS** [comment]
全部重装试过了，icqq也是0.3.10的，一样

> 合并转发消息发送失败了，估计是icqq问题可以尝试更新一次icqq版本库

**Comment by XiaoFuOS** [comment]
已解决，icqq问题，什么版本都报错，换回oicq正常发送
