### ISSUE TITLE
刷新ck时个别人只能绑定成功星铁的ck

### ISSUE THREAD

**Issue by VeritasAlex** [ctrlcvs/xiaoyao-cvs-plugin#80]
![QQ截图20230504180816](https://user-images.githubusercontent.com/57402050/236175096-680ed570-a0ff-455e-8a37-916a7fd85f13.png)
![QQ截图20230504180849](https://user-images.githubusercontent.com/57402050/236175108-5f39fa1c-32b5-42ca-af99-1e5b60a50b64.png)
目前只有他自己这种情况，其他人都能正常刷新。

**Comment by ctrlcvs** [comment]
cookie绑定逻辑是主体的，其次ck通用，前提是需要绑定游戏
