### ISSUE TITLE
扫码登录部分账号只会绑定星铁的ck 原神的ck绑定不上

### ISSUE THREAD

**Issue by LiSanSky** [ctrlcvs/xiaoyao-cvs-plugin#82]
扫码登录    部分账号只会绑定星铁的ck     原神的ck绑定不上  
![3d4c7c7d2b769ac1a0a64af097e90a8](https://user-images.githubusercontent.com/101582156/236379509-048cfb3c-5c8a-40f4-88fd-1f1c921ec1e8.jpg)

**Comment by ctrlcvs** [comment]
请考虑自己的原因，首先这个只是做了一个识别而且，至于ck为什么不能绑定原神的，用户账户有无绑定游戏，自己去确认

**Comment by ChaselDutt** [comment]
> 请考虑自己的原因，首先这个只是做了一个识别而且，至于ck为什么不能绑定原神的，用户账户有无绑定游戏，自己去确认

扫码登录的二维码扫出来只有原神，怎么扫星铁登录？

**Comment by ctrlcvs** [comment]
> > 请考虑自己的原因，首先这个只是做了一个识别而且，至于ck为什么不能绑定原神的，用户账户有无绑定游戏，自己去确认
> 
> 扫码登录的二维码扫出来只有原神，怎么扫星铁登录？

互通，如果你非要改成星铁的话可以在`xiaoyao-cvs-plugin/model/mys/mysTool`中把`app_id = 4` 改成`5`

**Comment by ctrlcvs** [comment]
> 扫码登录 部分账号只会绑定星铁的ck 原神的ck绑定不上 ![3d4c7c7d2b769ac1a0a64af097e90a8](https://user-images.githubusercontent.com/101582156/236379509-048cfb3c-5c8a-40f4-88fd-1f1c921ec1e8.jpg)

更新主体，主体绑定逻辑问题
