### ISSUE TITLE
刷新ck报错

### ISSUE THREAD

**Issue by xueqi5201314** [ctrlcvs/xiaoyao-cvs-plugin#83]
![Screenshot_20230505_150804.jpg](https://user-images.githubusercontent.com/108047693/236396789-17fe1896-d42a-4bcb-a727-7466fc5c87b7.jpg)

刷新ck没有响应，不知道成功了没有，今天早上出现的

**Comment by ctrlcvs** [comment]
更新主体，绑定逻辑是主体那边的方法
