### ISSUE TITLE
部分情况下，ck无法获取原神uid

### ISSUE THREAD

**Issue by liuyue96er** [ctrlcvs/xiaoyao-cvs-plugin#84]
米哈游通行证→账号游戏信息→星铁设为默认角色勾选
上述操作之后，#扫码登录，或者其他方法获取ck都没办法获取到原神的uid或者直接无法绑定

**Comment by liuyue96er** [comment]
看到其他ls也反馈过了，我目前的解决办法是，将ck的yaml的uid改成原神的，name由星穹改为天空岛。然后刷新ck重新获取星穹的ck，才会让其他各项功能恢复正常

**Comment by ctrlcvs** [comment]
更新云崽主体

**Comment by liuyue96er** [comment]
![QQ图片20230506180818](https://user-images.githubusercontent.com/106005062/236617893-548fb3b1-425e-49c7-929e-26e05a3e35d2.jpg)
我用的是trss脚本，喵崽，更新了，无效，跟#80那附近的几个ls一样的问题。我这边原本是一个群友有这个问题，我对比账号排查，让自己的号也复现了这个问题
就是在里面，原来是没有勾的，勾选上了，我就寄了，就变成上图的情况了
![QQ图片20230506180826](https://user-images.githubusercontent.com/106005062/236617898-067927f2-0f69-4f84-a018-803d279fb6f3.jpg)
我上面说的解决办法只是一个曲线救国，改uid
，可能是我描述的不清楚
我是把箭头指的地方，换成了原神的信息
![QQ图片20230506181700](https://user-images.githubusercontent.com/106005062/236618244-5fe19983-408a-4b9c-bd90-f2c10de46ba1.png)
然后#刷新ck，这份文件上面就会又出现铁道的信息，这时候才能有两个uid

**Comment by ctrlcvs** [comment]
你刚刚更新了？

**Comment by liuyue96er** [comment]
喵崽的更新日期在5月6日17点，我还尝试过重装，一样无效，xiaoyao是5月4日15点的

**Comment by ctrlcvs** [comment]
日志呢

**Comment by liuyue96er** [comment]
![E698F306045E0AFEFE66946AF97ADA42](https://user-images.githubusercontent.com/106005062/236618703-d679348e-6d31-4f5e-99cc-f3b0cc8b6110.jpg)
这个是扫码登录的日志
更新日志的话，我不会截，昨天重置的，都是trss上能下载的最新版本

**Comment by ctrlcvs** [comment]
你发#全部更新 就可以看见更新时间了

**Comment by liuyue96er** [comment]
![image](https://user-images.githubusercontent.com/106005062/236619922-5f23950e-b1cf-4b02-97a9-adc76988d22d.png)
![image](https://user-images.githubusercontent.com/106005062/236619947-b6a53859-3f7f-42b9-ab85-d3ea49eaa031.png)
![image](https://user-images.githubusercontent.com/106005062/236619980-4bfbaa9b-d7c1-43a4-b1a6-61fa4d7565e3.png)
然后问题依旧存在，跟前面发问题和日志是一样的，裂

**Comment by ctrlcvs** [comment]
更新喵崽再试试

**Comment by liuyue96er** [comment]
更新后就好了，谢谢佬
