### ISSUE TITLE
喵崽更新后stoken和cookie不识别

### ISSUE THREAD

**Issue by mxia9416** [ctrlcvs/xiaoyao-cvs-plugin#98]
如题，
之前用  #扫码登录 录入的ck和stoken，喵崽更新到最新后使用 #更新抽卡记录 会报错
“uid:undefined,authkey获取失败：请重新绑定stoken”
使用 #我的stoken 查询返回： ”您暂未绑定stoken”
签到功能也显示cookie失效
更新前都完好
已尝试使用命令#删除uid #删除ck等 删除ck uid stoken
再重新扫码  提示绑定成功 但还是相同问题

**Comment by TheTychoStar** [comment]
我这里也是一样的问题，不知道为什么，而且手动获取的cookie也不能用了。我怀疑是喵崽的问题？

**Comment by mxia9416** [comment]
确实是最新的喵崽重构了ck部分的代码，希望逍遥的作者可以适配一下更新，感谢🙏

**Comment by wayner6** [comment]
我是可以更新抽卡记录，但是一使用`#体力`就提示
```
米游社接口请求失败，暂时无法查询
米游社查询遇到验证码，请稍后再试
```
`#原石` 如下
![e99b06906e504e85fac289c2868f8dfd](https://github.com/ctrlcvs/xiaoyao-cvs-plugin/assets/88063517/595cb5d1-f2c3-450b-82fd-4d3983458ab8)
